In [ ]:
# ============================================================
# 03_analisis_sql_kpis.ipynb
# Carga de datos a PostgreSQL y análisis con SQL
# ============================================================

import geopandas as gpd
import pandas as pd
from sqlalchemy import create_engine, text
import os
import warnings
warnings.filterwarnings("ignore")

RUTA_PROCESSED = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed"

# ── Conexión a PostgreSQL ─────────────────────────────────────

DB_USER     = "postgres"
DB_PASSWORD = "***********"
DB_HOST     = "localhost"
DB_PORT     = "5433"
DB_NAME     = "mercado_inmobiliario"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# Verificar conexión
with engine.connect() as conn:
    version = conn.execute(text("SELECT version()")).scalar()
    print(f"✓ Conectado a PostgreSQL")
    print(f"  {version[:60]}...")

✓ Conectado a PostgreSQL
  PostgreSQL 18.1 on x86_64-windows, compiled by msvc-19.44.35...

In [3]:
# ── Cargar datos procesados ───────────────────────────────────
gdf = gpd.read_file(
    os.path.join(RUTA_PROCESSED, "bogota_valor_localidades.gpkg"),
    engine="pyogrio"
)

# Preparar DataFrame tabular (sin geometría para SQL)
df = pd.DataFrame(gdf.drop(columns="geometry"))
df = df.rename(columns={"año": "anio"})
df = df[["manzana_cod", "localidad", "valor_ref_m2", "anio"]].dropna()

print(f"✓ Dataset listo para cargar: {len(df):,} registros")
print(f"  Columnas: {df.columns.tolist()}")
print(f"  Años: {sorted(df['anio'].unique())}")
df.head(3)

✓ Dataset listo para cargar: 124,250 registros
  Columnas: ['manzana_cod', 'localidad', 'valor_ref_m2', 'anio']
  Años: [2021, 2022, 2024]

  manzana_cod       localidad  valor_ref_m2  anio
0   007401035  BARRIOS UNIDOS     3100000.0  2021
1   002592025            USME      590000.0  2021
2   007403017  BARRIOS UNIDOS     3200000.0  2021

In [ ]:
# ── Carga a PostgreSQL ────────────────────────────────────────
print("Cargando datos en PostgreSQL...")

df.to_sql(
    name="valor_referencia",
    con=engine,
    if_exists="append",    # append respeta el esquema ya creado
    index=False,
    chunksize=5000,        # carga en bloques de 5.000 filas
    method="multi"         # más eficiente 
)

# Verificar carga
with engine.connect() as conn:
    total = conn.execute(
        text("SELECT COUNT(*) FROM valor_referencia")
    ).scalar()
    por_anio = conn.execute(text("""
        SELECT anio, COUNT(*) as registros
        FROM valor_referencia
        GROUP BY anio
        ORDER BY anio
    """)).fetchall()

print(f"\n✓ Carga completada")
print(f"  Total registros en BD: {total:,}")
print(f"\n  Distribución por año:")
for anio, count in por_anio:
    print(f"    {anio}: {count:,} manzanas")

Cargando datos en PostgreSQL...

✓ Carga completada
  Total registros en BD: 248,495

  Distribución por año:
    2021: 82,538 manzanas
    2022: 82,531 manzanas
    2024: 83,426 manzanas

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text

# Reutilizacion del engine 
def sql(query, engine=engine):
    """Ejecuta una query y retorna DataFrame — helper del proyecto."""
    with engine.connect() as conn:
        return pd.read_sql(text(query), conn)

print("✓ Helper SQL listo")

✓ Helper SQL listo

In [ ]:
# ── QUERY 1: Estadísticas base ────────────────────────────────


q1 = """
SELECT
    localidad,
    anio,
    COUNT(*)                          AS total_manzanas,
    ROUND(AVG(valor_ref_m2))          AS valor_medio,
    ROUND(PERCENTILE_CONT(0.5)
          WITHIN GROUP (ORDER BY valor_ref_m2))
                                      AS valor_mediano,
    ROUND(MIN(valor_ref_m2))          AS valor_minimo,
    ROUND(MAX(valor_ref_m2))          AS valor_maximo,
    ROUND(STDDEV(valor_ref_m2))       AS desviacion_std,
    ROUND(PERCENTILE_CONT(0.25)
          WITHIN GROUP (ORDER BY valor_ref_m2))
                                      AS percentil_25,
    ROUND(PERCENTILE_CONT(0.75)
          WITHIN GROUP (ORDER BY valor_ref_m2))
                                      AS percentil_75
FROM valor_referencia
GROUP BY localidad, anio
ORDER BY localidad, anio;
"""

kpis_base = sql(q1)
print(f"✓ Query 1 ejecutada: {len(kpis_base)} filas")
kpis_base.head(6)

✓ Query 1 ejecutada: 58 filas

,localidad,anio,total_manzanas,valor_medio,valor_mediano,valor_minimo,valor_maximo,desviacion_std,percentil_25,percentil_75
0,ANTONIO NARIÑO,2021,1152,2493182.0,2362500.0,121302.0,5000000.0,703125.0,2200000.0,2850000.0
1,ANTONIO NARIÑO,2022,1152,2493182.0,2362500.0,121302.0,5000000.0,703125.0,2200000.0,2850000.0
2,ANTONIO NARIÑO,2024,1152,2871495.0,2820000.0,121607.0,5370000.0,778542.0,2570000.0,3300000.0
3,BARRIOS UNIDOS,2021,2396,2972300.0,3000000.0,61500.0,5000000.0,770008.0,2700000.0,3300000.0
4,BARRIOS UNIDOS,2022,2398,2971906.0,3000000.0,61500.0,5000000.0,769808.0,2700000.0,3300000.0
5,BARRIOS UNIDOS,2024,2396,3328813.0,3400000.0,153577.0,6070000.0,828774.0,3000000.0,3700000.0

In [ ]:
# ── QUERY 2: Variación año a año con LAG ─────────────────────
q2 = """
WITH base AS (
    SELECT
        localidad,
        anio,
        PERCENTILE_CONT(0.5)
            WITHIN GROUP (ORDER BY valor_ref_m2)    AS valor_mediano
    FROM valor_referencia
    GROUP BY localidad, anio
),
con_variacion AS (
    SELECT
        localidad,
        anio,
        valor_mediano,
        LAG(valor_mediano) OVER (
            PARTITION BY localidad ORDER BY anio
        )                                           AS valor_anio_anterior,
        LAG(anio) OVER (
            PARTITION BY localidad ORDER BY anio
        )                                           AS anio_anterior,
        ROUND(
            (
                (valor_mediano - LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                )) * 100.0 /
                NULLIF(LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                ), 0)
            )::numeric 
        , 2)                                        AS variacion_pct
    FROM base
)
SELECT
    localidad,
    anio,
    anio_anterior,
    ROUND(valor_mediano::numeric)       AS valor_mediano,
    ROUND(valor_anio_anterior::numeric) AS valor_anio_anterior,
    variacion_pct,
    CASE
        WHEN variacion_pct >= 20   THEN 'Alta valorización'
        WHEN variacion_pct >= 10   THEN 'Valorización moderada'
        WHEN variacion_pct >= 0    THEN 'Estable'
        WHEN variacion_pct IS NULL THEN 'Año base'
        ELSE                            'Desvalorización'
    END                                             AS categoria
FROM con_variacion
ORDER BY anio, variacion_pct DESC NULLS LAST;
"""
# linea 31 (::numeric)Es un detalle de tipado estricto que diferencia PostgreSQL de MySQL o SQL Server
variacion = sql(q2)
print(f"✓ Query 2 ejecutada: {len(variacion)} filas")
print(variacion[variacion["anio"] == 2024].to_string(index=False))

✓ Query 2 ejecutada: 58 filas
         localidad  anio  anio_anterior  valor_mediano  valor_anio_anterior  variacion_pct             categoria
        CANDELARIA  2024         2022.0      2700000.0            2000000.0          35.00     Alta valorización
     SAN CRISTOBAL  2024         2022.0      1070000.0             880000.0          21.59     Alta valorización
    CIUDAD BOLIVAR  2024         2022.0       824000.0             680000.0          21.18     Alta valorización
RAFAEL URIBE URIBE  2024         2022.0      1800000.0            1500000.0          20.00     Alta valorización
          FONTIBON  2024         2022.0      2330000.0            1950000.0          19.49 Valorización moderada
    ANTONIO NARIÑO  2024         2022.0      2820000.0            2362500.0          19.37 Valorización moderada
           KENNEDY  2024         2022.0      2480000.0            2100000.0          18.10 Valorización moderada
              BOSA  2024         2022.0      1900000.0            1650000.0          15.15 Valorización moderada
              SUBA  2024         2022.0      2660000.0            2315000.0          14.90 Valorización moderada
      LOS MARTIRES  2024         2022.0      2920000.0            2550000.0          14.51 Valorización moderada
        TUNJUELITO  2024         2022.0      2150000.0            1880000.0          14.36 Valorización moderada
     PUENTE ARANDA  2024         2022.0      2970000.0            2600000.0          14.23 Valorización moderada
    BARRIOS UNIDOS  2024         2022.0      3400000.0            3000000.0          13.33 Valorización moderada
          ENGATIVA  2024         2022.0      3000000.0            2650000.0          13.21 Valorización moderada
              USME  2024         2022.0       750000.0             670000.0          11.94 Valorización moderada
          SANTA FE  2024         2022.0      1220000.0            1100000.0          10.91 Valorización moderada
       TEUSAQUILLO  2024         2022.0      3400000.0            3100000.0           9.68               Estable
           USAQUEN  2024         2022.0      3100000.0            2885000.0           7.45               Estable
         CHAPINERO  2024         2022.0      4260000.0            5000000.0         -14.80       Desvalorización
           SUMAPAZ  2024            NaN        40000.0                  NaN            NaN              Año base

In [ ]:
# ── QUERY 3: Ranking de localidades por valor ─────────────────
q3 = """
WITH medianas AS (
    SELECT
        localidad,
        anio,
        PERCENTILE_CONT(0.5)
            WITHIN GROUP (ORDER BY valor_ref_m2)    AS valor_mediano
    FROM valor_referencia
    GROUP BY localidad, anio
)
SELECT
    anio,
    localidad,
    ROUND(valor_mediano::numeric)                               AS valor_mediano,
    RANK()       OVER (PARTITION BY anio ORDER BY valor_mediano DESC) AS rank_valor,
    DENSE_RANK() OVER (PARTITION BY anio ORDER BY valor_mediano DESC) AS dense_rank,
    NTILE(4)     OVER (PARTITION BY anio ORDER BY valor_mediano DESC) AS cuartil,
    ROUND((valor_mediano * 100.0 /
          SUM(valor_mediano) OVER (PARTITION BY anio))::numeric, 2) AS pct_sobre_total,
    ROUND((valor_mediano * 100.0 /
          AVG(valor_mediano) OVER (PARTITION BY anio))::numeric, 2) AS indice_vs_promedio
FROM medianas
ORDER BY anio, rank_valor;
"""
# linea 15 (::numeric)Es un detalle de tipado estricto que diferencia PostgreSQL de MySQL o SQL Server

ranking = sql(q3)
print(f"✓ Query 3 ejecutada: {len(ranking)} filas")
r2024 = ranking[ranking["anio"] == 2024]
print("\nTop 5 — Mayor valor:")
print(r2024.head(5).to_string(index=False))
print("\nBottom 5 — Menor valor:")
print(r2024.tail(5).to_string(index=False))

✓ Query 3 ejecutada: 58 filas

Top 5 — Mayor valor:
 anio      localidad  valor_mediano  rank_valor  dense_rank  cuartil  pct_sobre_total  indice_vs_promedio
 2024      CHAPINERO      4260000.0           1           1        1             9.30              186.05
 2024 BARRIOS UNIDOS      3400000.0           2           2        1             7.42              148.49
 2024    TEUSAQUILLO      3400000.0           2           2        1             7.42              148.49
 2024        USAQUEN      3100000.0           4           3        1             6.77              135.39
 2024       ENGATIVA      3000000.0           5           4        1             6.55              131.02

Bottom 5 — Menor valor:
 anio      localidad  valor_mediano  rank_valor  dense_rank  cuartil  pct_sobre_total  indice_vs_promedio
 2024       SANTA FE      1220000.0          16          15        4             2.66               53.28
 2024  SAN CRISTOBAL      1070000.0          17          16        4             2.34               46.73
 2024 CIUDAD BOLIVAR       824000.0          18          17        4             1.80               35.99
 2024           USME       750000.0          19          18        4             1.64               32.76
 2024        SUMAPAZ        40000.0          20          19        4             0.09                1.75

In [17]:
# ── QUERY 4: Índice de brecha — KPI de desigualdad ───────────
# Mide cuántas veces vale más el suelo en la localidad más cara vs la más barata

q4 = """
WITH medianas AS (
    SELECT
        localidad,
        anio,
        PERCENTILE_CONT(0.5)
            WITHIN GROUP (ORDER BY valor_ref_m2)    AS valor_mediano
    FROM valor_referencia
    GROUP BY localidad, anio
),
extremos AS (
    SELECT
        anio,
        MAX(valor_mediano)              AS valor_top,
        MIN(valor_mediano)              AS valor_bottom,
        AVG(valor_mediano)              AS valor_promedio
    FROM medianas
    GROUP BY anio
),
con_nombres AS (
    SELECT
        e.anio,
        e.valor_top,
        e.valor_bottom,
        e.valor_promedio,
        MAX(m.localidad)
            FILTER (WHERE m.valor_mediano = e.valor_top)    AS localidad_top,
        MAX(m.localidad)
            FILTER (WHERE m.valor_mediano = e.valor_bottom) AS localidad_bottom
    FROM extremos e
    JOIN medianas m ON m.anio = e.anio
    GROUP BY e.anio, e.valor_top, e.valor_bottom, e.valor_promedio
)
SELECT
    anio,
    localidad_top,
    ROUND(valor_top::numeric)                               AS valor_zona_premium,
    localidad_bottom,
    ROUND(valor_bottom::numeric)                            AS valor_zona_popular,
    ROUND((valor_top / NULLIF(valor_bottom,0))::numeric, 1) AS indice_brecha,
    ROUND(valor_promedio::numeric)                          AS valor_promedio_ciudad
FROM con_nombres
ORDER BY anio;
"""

brecha = sql(q4)
print("✓ Query 4 ejecutada — Índice de Brecha (KPI #3)")
print("=" * 60)
print(brecha.to_string(index=False))

✓ Query 4 ejecutada — Índice de Brecha (KPI #3)
============================================================
 anio localidad_top  valor_zona_premium localidad_bottom  valor_zona_popular  indice_brecha  valor_promedio_ciudad
 2021     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2022     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2024     CHAPINERO           4260000.0          SUMAPAZ             40000.0          106.5              2289700.0

In [18]:
# ── Poblar tabla kpis_localidad para Power BI ─────────────────
kpis_para_bd = sql("""
    SELECT
        localidad,
        anio,
        ROUND(PERCENTILE_CONT(0.5)
              WITHIN GROUP (ORDER BY valor_ref_m2)) AS valor_mediano,
        ROUND(AVG(valor_ref_m2))                    AS valor_medio,
        ROUND(MIN(valor_ref_m2))                    AS valor_minimo,
        ROUND(MAX(valor_ref_m2))                    AS valor_maximo,
        COUNT(*)                                    AS total_manzanas
    FROM valor_referencia
    GROUP BY localidad, anio
""")

kpis_para_bd.to_sql(
    name="kpis_localidad",
    con=engine,
    if_exists="replace",
    index=False
)
print(f"✓ Tabla kpis_localidad poblada: {len(kpis_para_bd)} filas")

# ── Exportar CSVs para Power BI ───────────────────────────────
RUTA_PROCESSED = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed"

exports = {
    "kpis_localidad.csv":     kpis_para_bd,
    "variacion_interanual.csv": variacion,
    "ranking_localidades.csv":  ranking,
    "indice_brecha.csv":        brecha,
}

for nombre, df in exports.items():
    ruta = f"{RUTA_PROCESSED}\\{nombre}"
    df.to_csv(ruta, index=False, encoding="utf-8-sig")  # utf-8-sig = compatible Excel
    print(f"  ✓ {nombre} — {len(df)} filas")

print("\n✓ Todos los CSVs listos para importar en Power BI")

✓ Tabla kpis_localidad poblada: 58 filas
  ✓ kpis_localidad.csv — 58 filas
  ✓ variacion_interanual.csv — 58 filas
  ✓ ranking_localidades.csv — 58 filas
  ✓ indice_brecha.csv — 3 filas

✓ Todos los CSVs listos para importar en Power BI

In [21]:
print(brecha.to_string(index=False))

 anio localidad_top  valor_zona_premium localidad_bottom  valor_zona_popular  indice_brecha  valor_promedio_ciudad
 2021     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2022     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2024     CHAPINERO           4260000.0          SUMAPAZ             40000.0          106.5              2289700.0

❗ Se esta presentando una inconsistencia con el indice de brecha para el año 2024

In [22]:
# Investigar Sumapaz en detalle
q_sumapaz = """
SELECT
    anio,
    localidad,
    COUNT(*)                                        AS manzanas,
    ROUND(MIN(valor_ref_m2)::numeric)               AS valor_min,
    ROUND(MAX(valor_ref_m2)::numeric)               AS valor_max,
    ROUND(AVG(valor_ref_m2)::numeric)               AS valor_medio,
    ROUND(PERCENTILE_CONT(0.5)
          WITHIN GROUP (ORDER BY valor_ref_m2)
          ::numeric)                                AS valor_mediano
FROM valor_referencia
WHERE localidad = 'SUMAPAZ'
GROUP BY anio, localidad
ORDER BY anio;
"""
print(sql(q_sumapaz).to_string(index=False))

# Ver los valores más bajos de Sumapaz en 2024
q_detalle = """
SELECT manzana_cod, valor_ref_m2, anio
FROM valor_referencia
WHERE localidad = 'SUMAPAZ' AND anio = 2024
ORDER BY valor_ref_m2 ASC
LIMIT 10;
"""
print(sql(q_detalle).to_string(index=False))

 anio localidad  manzanas  valor_min  valor_max  valor_medio  valor_mediano
 2024   SUMAPAZ        38     6235.0    40000.0      34937.0        40000.0
manzana_cod  valor_ref_m2  anio
  209106002        6235.0  2024
  209106002        6235.0  2024
  209104010       20585.0  2024
  209104010       20585.0  2024
  209106003       23325.0  2024
  209106003       23325.0  2024
  209104002       30000.0  2024
  209104002       30000.0  2024
  203106006       35000.0  2024
  209104004       35000.0  2024

❗❗❗Manzana_cod duplicadas para el mismo año❗❗❗

In [23]:
q_fix = """
-- Ver magnitud del problema de duplicados
SELECT
    anio,
    COUNT(*)                        AS registros_totales,
    COUNT(DISTINCT manzana_cod)     AS manzanas_unicas,
    COUNT(*) - COUNT(DISTINCT manzana_cod) AS duplicados
FROM valor_referencia
GROUP BY anio
ORDER BY anio;
"""
print(sql(q_fix).to_string(index=False))

 anio  registros_totales  manzanas_unicas  duplicados
 2021              82538            41269       41269
 2022              82532            41265       41267
 2024              83430            41711       41719

In [24]:
# Actualizar la tabla kpis_localidad excluyendo Sumapaz de urbanos
q_kpis_urbano = """
-- Recrear kpis con flag urbano/rural
SELECT
    localidad,
    anio,
    CASE WHEN localidad = 'SUMAPAZ' THEN 'Rural'
         ELSE 'Urbano' END                              AS tipo_suelo,
    COUNT(*)                                            AS total_manzanas,
    ROUND(PERCENTILE_CONT(0.5)
          WITHIN GROUP (ORDER BY valor_ref_m2)
          ::numeric)                                    AS valor_mediano,
    ROUND(AVG(valor_ref_m2)::numeric)                   AS valor_medio,
    ROUND(MIN(valor_ref_m2)::numeric)                   AS valor_minimo,
    ROUND(MAX(valor_ref_m2)::numeric)                   AS valor_maximo
FROM valor_referencia
GROUP BY localidad, anio
ORDER BY tipo_suelo, localidad, anio;
"""

kpis_v2 = sql(q_kpis_urbano)

# Sobrescribir en BD y CSV
kpis_v2.to_sql("kpis_localidad", con=engine, if_exists="replace", index=False)

ruta = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed\kpis_localidad.csv"
kpis_v2.to_csv(ruta, index=False, encoding="utf-8-sig")

print(f"✓ Tabla kpis_localidad actualizada: {len(kpis_v2)} filas")
print(f"\nDistribución por tipo:")
print(kpis_v2.groupby("tipo_suelo")["localidad"].nunique().to_string())

✓ Tabla kpis_localidad actualizada: 58 filas

Distribución por tipo:
tipo_suelo
Rural      1
Urbano    19

In [25]:
q_brecha_v2 = """
WITH medianas AS (
    SELECT
        localidad,
        anio,
        PERCENTILE_CONT(0.5)
            WITHIN GROUP (ORDER BY valor_ref_m2)    AS valor_mediano
    FROM valor_referencia
    WHERE localidad != 'SUMAPAZ'          -- solo zonas urbanas comparables
    GROUP BY localidad, anio
),
extremos AS (
    SELECT
        anio,
        MAX(valor_mediano)              AS valor_top,
        MIN(valor_mediano)              AS valor_bottom,
        AVG(valor_mediano)              AS valor_promedio
    FROM medianas
    GROUP BY anio
),
con_nombres AS (
    SELECT
        e.anio,
        e.valor_top,
        e.valor_bottom,
        e.valor_promedio,
        MAX(m.localidad)
            FILTER (WHERE m.valor_mediano = e.valor_top)    AS localidad_top,
        MAX(m.localidad)
            FILTER (WHERE m.valor_mediano = e.valor_bottom) AS localidad_bottom
    FROM extremos e
    JOIN medianas m ON m.anio = e.anio
    GROUP BY e.anio, e.valor_top, e.valor_bottom, e.valor_promedio
)
SELECT
    anio,
    localidad_top,
    ROUND(valor_top::numeric)                                AS valor_zona_premium,
    localidad_bottom,
    ROUND(valor_bottom::numeric)                             AS valor_zona_popular,
    ROUND((valor_top / NULLIF(valor_bottom,0))::numeric, 1) AS indice_brecha,
    ROUND(valor_promedio::numeric)                           AS valor_promedio_ciudad
FROM con_nombres
ORDER BY anio;
"""

brecha_v2 = sql(q_brecha_v2)
print("KPI #3 — Índice de Brecha (solo localidades urbanas)")
print("=" * 65)
print(brecha_v2.to_string(index=False))

# Guardar versión corregida
ruta_b = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed\indice_brecha.csv"
brecha_v2.to_csv(ruta_b, index=False, encoding="utf-8-sig")
print("\n✓ indice_brecha.csv actualizado")

KPI #3 — Índice de Brecha (solo localidades urbanas)
=================================================================
 anio localidad_top  valor_zona_premium localidad_bottom  valor_zona_popular  indice_brecha  valor_promedio_ciudad
 2021     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2022     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2024     CHAPINERO           4260000.0             USME            750000.0            5.7              2408105.0

✓ indice_brecha.csv actualizado

In [26]:
# Ver si una misma manzana tiene dos localidades distintas o la misma
q_check = """
SELECT
    manzana_cod,
    anio,
    COUNT(*)            AS veces,
    COUNT(DISTINCT localidad) AS localidades_distintas,
    STRING_AGG(localidad, ' | ' ORDER BY localidad) AS localidades
FROM valor_referencia
WHERE anio = 2024
GROUP BY manzana_cod, anio
HAVING COUNT(*) > 1
LIMIT 10;
"""
print(sql(q_check).to_string(index=False))

manzana_cod  anio  veces  localidades_distintas                   localidades
  001101001  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101002  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101003  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101004  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101005  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101006  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101007  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101008  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101009  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL
  001101013  2024      2                      1 SAN CRISTOBAL | SAN CRISTOBAL

In [27]:
# Comparar medianas con y sin duplicados
q_impacto = """
WITH sin_duplicados AS (
    SELECT DISTINCT ON (manzana_cod, anio)
        manzana_cod, localidad, valor_ref_m2, anio
    FROM valor_referencia
    ORDER BY manzana_cod, anio, valor_ref_m2
)
SELECT
    anio,
    COUNT(*)                                        AS manzanas,
    ROUND(PERCENTILE_CONT(0.5)
          WITHIN GROUP (ORDER BY valor_ref_m2)
          ::numeric)                                AS mediana_sin_dup,
    ROUND(AVG(valor_ref_m2)::numeric)               AS media_sin_dup
FROM sin_duplicados
GROUP BY anio
ORDER BY anio;
"""
print(sql(q_impacto).to_string(index=False))

 anio  manzanas  mediana_sin_dup  media_sin_dup
 2021     41269        1900000.0      1957525.0
 2022     41265        1900000.0      1957418.0
 2024     41711        2150000.0      2208161.0

🎯 Deduplicar directamente en PostgreSQL

In [28]:
# ── Paso 1: Crear tabla limpia sin duplicados ─────────────────
q_dedup = """
-- Crear tabla limpia con DISTINCT ON (forma idiomática en PostgreSQL)
CREATE TABLE valor_referencia_clean AS
SELECT DISTINCT ON (manzana_cod, anio)
    manzana_cod,
    localidad,
    valor_ref_m2,
    anio
FROM valor_referencia
ORDER BY manzana_cod, anio, valor_ref_m2;
"""

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS valor_referencia_clean;"))
    conn.execute(text(q_dedup))
    conn.execute(text("""
        CREATE INDEX idx_clean_localidad ON valor_referencia_clean(localidad);
        CREATE INDEX idx_clean_anio      ON valor_referencia_clean(anio);
    """))
    conn.commit()
    total = conn.execute(
        text("SELECT COUNT(*) FROM valor_referencia_clean")
    ).scalar()
    print(f"✓ Tabla limpia creada: {total:,} registros")

# Verificar que no hay duplicados
check = sql("""
    SELECT anio, COUNT(*) AS registros, COUNT(DISTINCT manzana_cod) AS unicas
    FROM valor_referencia_clean
    GROUP BY anio ORDER BY anio;
""")
print(check.to_string(index=False))

✓ Tabla limpia creada: 124,245 registros
 anio  registros  unicas
 2021      41269   41269
 2022      41265   41265
 2024      41711   41711

In [29]:
# ── Paso 2: Reemplazar tabla original ─────────────────────────
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS valor_referencia;"))
    conn.execute(text("""
        ALTER TABLE valor_referencia_clean
        RENAME TO valor_referencia;
    """))
    conn.execute(text("""
        CREATE INDEX idx_vr_localidad ON valor_referencia(localidad);
        CREATE INDEX idx_vr_anio      ON valor_referencia(anio);
        CREATE INDEX idx_vr_manzana   ON valor_referencia(manzana_cod);
    """))
    conn.commit()
    print("✓ Tabla valor_referencia reemplazada con versión limpia")

✓ Tabla valor_referencia reemplazada con versión limpia

In [30]:
# ── Paso 3: Recalcular y repoblar kpis_localidad ──────────────
kpis_final = sql("""
    SELECT
        localidad,
        anio,
        CASE WHEN localidad = 'SUMAPAZ' THEN 'Rural'
             ELSE 'Urbano' END                              AS tipo_suelo,
        COUNT(*)                                            AS total_manzanas,
        ROUND(PERCENTILE_CONT(0.5)
              WITHIN GROUP (ORDER BY valor_ref_m2)
              ::numeric)                                    AS valor_mediano,
        ROUND(AVG(valor_ref_m2)::numeric)                   AS valor_medio,
        ROUND(MIN(valor_ref_m2)::numeric)                   AS valor_minimo,
        ROUND(MAX(valor_ref_m2)::numeric)                   AS valor_maximo,
        ROUND(STDDEV(valor_ref_m2)::numeric)                AS desviacion_std
    FROM valor_referencia
    GROUP BY localidad, anio
    ORDER BY tipo_suelo, localidad, anio;
""")

kpis_final.to_sql("kpis_localidad", con=engine, if_exists="replace", index=False)
print(f"✓ kpis_localidad recalculada: {len(kpis_final)} filas")
print(kpis_final[kpis_final["tipo_suelo"]=="Urbano"][
    ["localidad","anio","total_manzanas","valor_mediano"]
].to_string(index=False))

✓ kpis_localidad recalculada: 58 filas
         localidad  anio  total_manzanas  valor_mediano
    ANTONIO NARIÑO  2021             576      2362500.0
    ANTONIO NARIÑO  2022             576      2362500.0
    ANTONIO NARIÑO  2024             576      2820000.0
    BARRIOS UNIDOS  2021            1198      3000000.0
    BARRIOS UNIDOS  2022            1198      3000000.0
    BARRIOS UNIDOS  2024            1198      3400000.0
              BOSA  2021            3129      1650000.0
              BOSA  2022            3129      1650000.0
              BOSA  2024            3211      1900000.0
        CANDELARIA  2021             164      2000000.0
        CANDELARIA  2022             164      2000000.0
        CANDELARIA  2024             163      2700000.0
         CHAPINERO  2021             920      5000000.0
         CHAPINERO  2022             920      5000000.0
         CHAPINERO  2024            1016      4260000.0
    CIUDAD BOLIVAR  2021            4915       680000.0
    CIUDAD BOLIVAR  2022            4915       680000.0
    CIUDAD BOLIVAR  2024            4918       824000.0
          ENGATIVA  2021            4106      2650000.0
          ENGATIVA  2022            4106      2650000.0
          ENGATIVA  2024            4110      3000000.0
          FONTIBON  2021            1585      1950000.0
          FONTIBON  2022            1585      1950000.0
          FONTIBON  2024            1598      2330000.0
           KENNEDY  2021            4674      2100000.0
           KENNEDY  2022            4674      2100000.0
           KENNEDY  2024            4761      2480000.0
      LOS MARTIRES  2021             696      2550000.0
      LOS MARTIRES  2022             696      2550000.0
      LOS MARTIRES  2024             698      2920000.0
     PUENTE ARANDA  2021            1733      2600000.0
     PUENTE ARANDA  2022            1733      2600000.0
     PUENTE ARANDA  2024            1733      2970000.0
RAFAEL URIBE URIBE  2021            2496      1500000.0
RAFAEL URIBE URIBE  2022            2496      1500000.0
RAFAEL URIBE URIBE  2024            2492      1800000.0
     SAN CRISTOBAL  2021            2804       880000.0
     SAN CRISTOBAL  2022            2803       880000.0
     SAN CRISTOBAL  2024            2821      1070000.0
          SANTA FE  2021             708      1100000.0
          SANTA FE  2022             705      1100000.0
          SANTA FE  2024             709      1220000.0
              SUBA  2021            4633      2315000.0
              SUBA  2022            4633      2315000.0
              SUBA  2024            4627      2660000.0
       TEUSAQUILLO  2021             977      3100000.0
       TEUSAQUILLO  2022             977      3100000.0
       TEUSAQUILLO  2024             979      3400000.0
        TUNJUELITO  2021             784      1880000.0
        TUNJUELITO  2022             784      1880000.0
        TUNJUELITO  2024             787      2150000.0
           USAQUEN  2021            2188      2885000.0
           USAQUEN  2022            2188      2885000.0
           USAQUEN  2024            2231      3100000.0
              USME  2021            2983       670000.0
              USME  2022            2983       670000.0
              USME  2024            3064       750000.0

In [31]:
# ── Paso 4: Reexportar todos los CSVs finales ─────────────────
RUTA = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed"

# Recalcular variacion y ranking sobre tabla limpia
variacion_final = sql("""
    WITH base AS (
        SELECT localidad, anio,
               PERCENTILE_CONT(0.5)
                   WITHIN GROUP (ORDER BY valor_ref_m2) AS valor_mediano
        FROM valor_referencia
        GROUP BY localidad, anio
    )
    SELECT
        localidad, anio,
        ROUND(valor_mediano::numeric)                        AS valor_mediano,
        ROUND(LAG(valor_mediano) OVER (
            PARTITION BY localidad ORDER BY anio
        )::numeric)                                          AS valor_anio_anterior,
        LAG(anio) OVER (
            PARTITION BY localidad ORDER BY anio
        )                                                    AS anio_anterior,
        ROUND((
            (valor_mediano - LAG(valor_mediano) OVER (
                PARTITION BY localidad ORDER BY anio
            )) * 100.0 / NULLIF(LAG(valor_mediano) OVER (
                PARTITION BY localidad ORDER BY anio
            ), 0)
        )::numeric, 2)                                       AS variacion_pct,
        CASE
            WHEN ROUND((
                (valor_mediano - LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                )) * 100.0 / NULLIF(LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                ), 0)
            )::numeric, 2) >= 20   THEN 'Alta valorización'
            WHEN ROUND((
                (valor_mediano - LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                )) * 100.0 / NULLIF(LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                ), 0)
            )::numeric, 2) >= 10   THEN 'Valorización moderada'
            WHEN LAG(valor_mediano) OVER (
                PARTITION BY localidad ORDER BY anio
            ) IS NULL              THEN 'Año base'
            ELSE                        'Estable'
        END                                                  AS categoria
    FROM base
    ORDER BY anio, variacion_pct DESC NULLS LAST;
""")

exports = {
    "kpis_localidad.csv":      kpis_final,
    "variacion_interanual.csv": variacion_final,
}

for nombre, df in exports.items():
    df.to_csv(f"{RUTA}\\{nombre}", index=False, encoding="utf-8-sig")
    print(f"  ✓ {nombre} — {len(df)} filas")

print("\n✓ Base de datos y CSVs 100% limpios y listos para Power BI")

  ✓ kpis_localidad.csv — 58 filas
  ✓ variacion_interanual.csv — 58 filas

✓ Base de datos y CSVs 100% limpios y listos para Power BI

In [32]:
from sqlalchemy import create_engine, text
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:Skyler2026*@localhost:5433/mercado_inmobiliario"
)

RUTA = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed"

# ── Regenerar indice_brecha desde la tabla limpia ─────────────
brecha_final = pd.read_sql(text("""
    WITH medianas AS (
        SELECT
            localidad,
            anio,
            PERCENTILE_CONT(0.5)
                WITHIN GROUP (ORDER BY valor_ref_m2) AS valor_mediano
        FROM valor_referencia
        WHERE localidad != 'SUMAPAZ'
        GROUP BY localidad, anio
    ),
    extremos AS (
        SELECT
            anio,
            MAX(valor_mediano) AS valor_top,
            MIN(valor_mediano) AS valor_bottom,
            AVG(valor_mediano) AS valor_promedio
        FROM medianas
        GROUP BY anio
    ),
    con_nombres AS (
        SELECT
            e.anio,
            e.valor_top,
            e.valor_bottom,
            e.valor_promedio,
            MAX(m.localidad)
                FILTER (WHERE m.valor_mediano = e.valor_top)    AS localidad_top,
            MAX(m.localidad)
                FILTER (WHERE m.valor_mediano = e.valor_bottom) AS localidad_bottom
        FROM extremos e
        JOIN medianas m ON m.anio = e.anio
        GROUP BY e.anio, e.valor_top, e.valor_bottom, e.valor_promedio
    )
    SELECT
        anio,
        localidad_top,
        ROUND(valor_top::numeric)                                AS valor_zona_premium,
        localidad_bottom,
        ROUND(valor_bottom::numeric)                             AS valor_zona_popular,
        ROUND((valor_top / NULLIF(valor_bottom,0))::numeric, 1) AS indice_brecha,
        ROUND(valor_promedio::numeric)                           AS valor_promedio_ciudad
    FROM con_nombres
    ORDER BY anio;
"""), engine)

print("Indice de brecha actualizado:")
print(brecha_final.to_string(index=False))

# Guardar
brecha_final.to_csv(f"{RUTA}\\indice_brecha.csv", index=False, encoding="utf-8-sig")

# Guardar también en PostgreSQL
brecha_final.to_sql("indice_brecha", con=engine, if_exists="replace", index=False)

print("\n✓ CSV e tabla PostgreSQL actualizados")

Indice de brecha actualizado:
 anio localidad_top  valor_zona_premium localidad_bottom  valor_zona_popular  indice_brecha  valor_promedio_ciudad
 2021     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2022     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2024     CHAPINERO           4260000.0             USME            750000.0            5.7              2408105.0

✓ CSV e tabla PostgreSQL actualizados

In [33]:
# Diagnóstico rápido
with engine.connect() as conn:
    vr = conn.execute(text("SELECT COUNT(*) FROM valor_referencia")).scalar()
    kpi = conn.execute(text("SELECT COUNT(*) FROM kpis_localidad")).scalar()
    print(f"valor_referencia : {vr:,} registros")
    print(f"kpis_localidad   : {kpi:,} registros")

valor_referencia : 124,245 registros
kpis_localidad   : 58 registros

In [34]:
# Query simplificada y robusta
brecha_final = pd.read_sql(text("""
    WITH medianas AS (
        SELECT
            localidad,
            anio,
            PERCENTILE_CONT(0.5)
                WITHIN GROUP (ORDER BY valor_ref_m2) AS valor_mediano
        FROM valor_referencia
        WHERE localidad != 'SUMAPAZ'
          AND localidad IS NOT NULL
        GROUP BY localidad, anio
    ),
    rankings AS (
        SELECT
            localidad,
            anio,
            valor_mediano,
            RANK() OVER (PARTITION BY anio ORDER BY valor_mediano DESC) AS rank_desc,
            RANK() OVER (PARTITION BY anio ORDER BY valor_mediano ASC)  AS rank_asc
        FROM medianas
    ),
    extremos AS (
        SELECT
            anio,
            MAX(CASE WHEN rank_desc = 1 THEN localidad END) AS localidad_top,
            MAX(CASE WHEN rank_desc = 1 THEN valor_mediano END) AS valor_top,
            MAX(CASE WHEN rank_asc  = 1 THEN localidad END) AS localidad_bottom,
            MAX(CASE WHEN rank_asc  = 1 THEN valor_mediano END) AS valor_bottom,
            AVG(valor_mediano) AS valor_promedio
        FROM rankings
        GROUP BY anio
    )
    SELECT
        anio,
        localidad_top,
        ROUND(valor_top::numeric)                                AS valor_zona_premium,
        localidad_bottom,
        ROUND(valor_bottom::numeric)                             AS valor_zona_popular,
        ROUND((valor_top / NULLIF(valor_bottom, 0))::numeric, 1) AS indice_brecha,
        ROUND(valor_promedio::numeric)                           AS valor_promedio_ciudad
    FROM extremos
    ORDER BY anio;
"""), engine)

print(f"Filas retornadas: {len(brecha_final)}")
print(brecha_final.to_string(index=False))

Filas retornadas: 3
 anio localidad_top  valor_zona_premium localidad_bottom  valor_zona_popular  indice_brecha  valor_promedio_ciudad
 2021     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2022     CHAPINERO           5000000.0             USME            670000.0            7.5              2151184.0
 2024     CHAPINERO           4260000.0             USME            750000.0            5.7              2408105.0

In [35]:
RUTA = r"C:\Users\kenpa\OneDrive\Desktop\FORMACION\colombia-mercado-inmobiliario\data\processed"

# ── 1. Guardar indice_brecha en PostgreSQL y CSV ──────────────
brecha_final.to_sql("indice_brecha", con=engine, if_exists="replace", index=False)
brecha_final.to_csv(f"{RUTA}\\indice_brecha.csv", index=False, encoding="utf-8-sig")
print(f"✓ indice_brecha: {len(brecha_final)} filas")

# ── 2. Regenerar variacion_interanual ─────────────────────────
variacion_final = pd.read_sql(text("""
    WITH base AS (
        SELECT
            localidad,
            anio,
            PERCENTILE_CONT(0.5)
                WITHIN GROUP (ORDER BY valor_ref_m2) AS valor_mediano
        FROM valor_referencia
        GROUP BY localidad, anio
    ),
    rankings AS (
        SELECT
            localidad,
            anio,
            ROUND(valor_mediano::numeric)                        AS valor_mediano,
            ROUND(LAG(valor_mediano) OVER (
                PARTITION BY localidad ORDER BY anio
            )::numeric)                                          AS valor_anio_anterior,
            LAG(anio) OVER (
                PARTITION BY localidad ORDER BY anio
            )                                                    AS anio_anterior,
            ROUND((
                (valor_mediano - LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                )) * 100.0 / NULLIF(LAG(valor_mediano) OVER (
                    PARTITION BY localidad ORDER BY anio
                ), 0)
            )::numeric, 2)                                       AS variacion_pct
        FROM base
    )
    SELECT
        localidad,
        anio,
        anio_anterior,
        valor_mediano,
        valor_anio_anterior,
        variacion_pct,
        CASE
            WHEN variacion_pct >= 20   THEN 'Alta valorización'
            WHEN variacion_pct >= 10   THEN 'Valorización moderada'
            WHEN variacion_pct >= 0    THEN 'Estable'
            WHEN variacion_pct IS NULL THEN 'Año base'
            ELSE                            'Desvalorización'
        END AS categoria
    FROM rankings
    ORDER BY anio, variacion_pct DESC NULLS LAST;
"""), engine)

variacion_final.to_sql("variacion_interanual", con=engine, if_exists="replace", index=False)
variacion_final.to_csv(f"{RUTA}\\variacion_interanual.csv", index=False, encoding="utf-8-sig")
print(f"✓ variacion_interanual: {len(variacion_final)} filas")

# ── 3. Verificar las 3 tablas en PostgreSQL ───────────────────
with engine.connect() as conn:
    for tabla in ["valor_referencia", "kpis_localidad",
                  "indice_brecha", "variacion_interanual"]:
        n = conn.execute(text(f"SELECT COUNT(*) FROM {tabla}")).scalar()
        print(f"  ✓ {tabla:<25} {n:>6} filas")

print("\n✓ PostgreSQL y CSVs 100% sincronizados")

✓ indice_brecha: 3 filas
✓ variacion_interanual: 58 filas
  ✓ valor_referencia          124245 filas
  ✓ kpis_localidad                58 filas
  ✓ indice_brecha                  3 filas
  ✓ variacion_interanual          58 filas

✓ PostgreSQL y CSVs 100% sincronizados

In [36]:
check = pd.read_sql(text("""
    SELECT
        anio,
        ROUND(PERCENTILE_CONT(0.5)
              WITHIN GROUP (ORDER BY valor_ref_m2)
              ::numeric) AS mediana_urbano
    FROM valor_referencia
    WHERE localidad != 'SUMAPAZ'
    GROUP BY anio
    ORDER BY anio;
"""), engine)
print(check.to_string(index=False))

 anio  mediana_urbano
 2021       1900000.0
 2022       1900000.0
 2024       2150000.0

   ❗❗ ❗Ocurre un error al intentar representar la varianza porcentual año por año, esto debido a que sumapaz hace parte del promedio general kpis_localidad aun cuando se hace la filtracion por tipo de suelo. ❗❗❗

In [37]:
# Tabla resumen ciudad — mediana real por año sin Sumapaz
resumen_ciudad = pd.read_sql(text("""
    SELECT
        anio,
        'Urbano'                                            AS tipo_suelo,
        COUNT(*)                                            AS total_manzanas,
        ROUND(PERCENTILE_CONT(0.5)
              WITHIN GROUP (ORDER BY valor_ref_m2)
              ::numeric)                                    AS valor_mediano_ciudad,
        ROUND(AVG(valor_ref_m2)::numeric)                   AS valor_medio_ciudad,
        ROUND(MIN(valor_ref_m2)::numeric)                   AS valor_minimo_ciudad,
        ROUND(MAX(valor_ref_m2)::numeric)                   AS valor_maximo_ciudad
    FROM valor_referencia
    WHERE localidad != 'SUMAPAZ'
    GROUP BY anio
    ORDER BY anio;
"""), engine)

print(resumen_ciudad.to_string(index=False))

# Guardar
resumen_ciudad.to_sql(
    "resumen_ciudad", con=engine,
    if_exists="replace", index=False
)
resumen_ciudad.to_csv(
    f"{RUTA}\\resumen_ciudad.csv",
    index=False, encoding="utf-8-sig", decimal=",", sep=";"
)
print("✓ resumen_ciudad guardado en PostgreSQL y CSV")

 anio tipo_suelo  total_manzanas  valor_mediano_ciudad  valor_medio_ciudad  valor_minimo_ciudad  valor_maximo_ciudad
 2021     Urbano           41269             1900000.0           1957525.0               8300.0            8700000.0
 2022     Urbano           41265             1900000.0           1957418.0               8300.0            8700000.0
 2024     Urbano           41692             2150000.0           2209152.0               3800.0            9550000.0
✓ resumen_ciudad guardado en PostgreSQL y CSV

In [5]:
check = pd.read_sql(text("""
    SELECT localidad, anio, variacion_pct, categoria
    FROM variacion_interanual
    WHERE anio = 2024
    ORDER BY variacion_pct ASC;
"""), engine)
print(check.to_string(index=False))

         localidad  anio  variacion_pct             categoria
         CHAPINERO  2024         -14.80       Desvalorización
           USAQUEN  2024           7.45               Estable
       TEUSAQUILLO  2024           9.68               Estable
          SANTA FE  2024          10.91 Valorización moderada
              USME  2024          11.94 Valorización moderada
          ENGATIVA  2024          13.21 Valorización moderada
    BARRIOS UNIDOS  2024          13.33 Valorización moderada
     PUENTE ARANDA  2024          14.23 Valorización moderada
        TUNJUELITO  2024          14.36 Valorización moderada
      LOS MARTIRES  2024          14.51 Valorización moderada
              SUBA  2024          14.90 Valorización moderada
              BOSA  2024          15.15 Valorización moderada
           KENNEDY  2024          18.10 Valorización moderada
    ANTONIO NARIÑO  2024          19.37 Valorización moderada
          FONTIBON  2024          19.49 Valorización moderada
RAFAEL URIBE URIBE  2024          20.00     Alta valorización
    CIUDAD BOLIVAR  2024          21.18     Alta valorización
     SAN CRISTOBAL  2024          21.59     Alta valorización
        CANDELARIA  2024          35.00     Alta valorización
           SUMAPAZ  2024            NaN              Año base